### ISSUE TITLE
please update pr

### ISSUE THREAD

**Issue by langdon** [BU-Spark/se-muckrock-calendar#26]
please update #25 with [commit to fix casing](https://github.com/BU-Spark/se-muckrock-calendar/commit/04e57fccf2f8984328558275e7db02a2ca9b1109)

**Comment by emcateer27** [comment]
When I go onto the pull request it seems as though it has been added as a commit. Please confirm you are seeing the same as the screenshot:
<img width="1440" alt="Screen Shot 2021-12-21 at 4 24 52 PM" src="https://user-images.githubusercontent.com/60163579/146999656-715a9e79-4c50-4574-a77c-88d51fcbe8ff.png">
.

**Comment by langdon** [comment]
oh, weird. I thought the original PR author had to update it. Sorry for the noise.
